# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nlogLikPW_uni <- function(para, y, delta, X, basis, dbasis, weights) {
    .Call(`_SemiCompRisksFreq_nlogLikPW_uni`, para, y, delta, X, basis, dbasis, weights)
}

ngradPW_uni <- function(para, y, delta, X, basis, dbasis, weights) {
    .Call(`_SemiCompRisksFreq_ngradPW_uni`, para, y, delta, X, basis, dbasis, weights)
}

ngradPW_uni_mat <- function(para, y, delta, X, basis, dbasis, weights) {
    .Call(`_SemiCompRisksFreq_ngradPW_uni_mat`, para, y, delta, X, basis, dbasis, weights)
}

nlogLikPW_ID <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_nlogLikPW_ID`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind)
}

ngradPW_ID <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradPW_ID`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind)
}

ngradPW_ID_mat <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradPW_ID_mat`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, weights, frailty_ind)
}

nlogLikRP_uni <- function(para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_nlogLikRP_uni`, para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights)
}

ngradRP_uni <- function(para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_ngradRP_uni`, para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights)
}

ngradRP_uni_mat <- function(para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_ngradRP_uni_mat`, para, y, delta, X, basis, dbasis, basis_yL, anyLT, weights)
}

nlogLikRP_ID <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_nlogLikRP_ID`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind)
}

ngradRP_ID <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradRP_ID`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind)
}

ngradRP_ID_mat <- function(para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradRP_ID_mat`, para, y1, y2, delta1, delta2, anyLT, X1, X2, X3, basis1, basis2, basis3, basis3_y1, basis1_yL, basis2_yL, dbasis1, dbasis2, dbasis3, model, weights, frailty_ind)
}

nlogLikBS_uni <- function(para, y, delta, X, basis, weights, quad_weights) {
    .Call(`_SemiCompRisksFreq_nlogLikBS_uni`, para, y, delta, X, basis, weights, quad_weights)
}

ngradBS_uni <- function(para, y, delta, X, basis, weights, quad_weights) {
    .Call(`_SemiCompRisksFreq_ngradBS_uni`, para, y, delta, X, basis, weights, quad_weights)
}

ngradBS_uni_mat <- function(para, y, delta, X, basis, weights, quad_weights) {
    .Call(`_SemiCompRisksFreq_ngradBS_uni_mat`, para, y, delta, X, basis, weights, quad_weights)
}

nlogLikBS_ID <- function(para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_nlogLikBS_ID`, para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind)
}

ngradBS_ID <- function(para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradBS_ID`, para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind)
}

ngradBS_ID_mat <- function(para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradBS_ID_mat`, para, y1, y2, delta1, delta2, yL, anyLT, X1, X2, X3, basis1, basis2, basis3, basis1_yL, basis2_yL, weights, quad_weights, frailty_ind)
}

nlogLikWB_uni <- function(para, y, delta, X, yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_nlogLikWB_uni`, para, y, delta, X, yL, anyLT, weights)
}

ngradWB_uni <- function(para, y, delta, X, yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_ngradWB_uni`, para, y, delta, X, yL, anyLT, weights)
}

ngradWB_uni_mat <- function(para, y, delta, X, yL, anyLT, weights) {
    .Call(`_SemiCompRisksFreq_ngradWB_uni_mat`, para, y, delta, X, yL, anyLT, weights)
}

nlogLikWB_ID <- function(para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_nlogLikWB_ID`, para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind)
}

ngradWB_ID <- function(para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradWB_ID`, para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind)
}

ngradWB_ID_mat <- function(para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_ngradWB_ID_mat`, para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind)
}

nhessWB_ID_frail_SM <- function(para, y1, y2, delta1, delta2, X1, X2, X3) {
    .Call(`_SemiCompRisksFreq_nhessWB_ID_frail_SM`, para, y1, y2, delta1, delta2, X1, X2, X3)
}

nhessWB_ID_frail_M <- function(para, y1, y2, delta1, delta2, X1, X2, X3) {
    .Call(`_SemiCompRisksFreq_nhessWB_ID_frail_M`, para, y1, y2, delta1, delta2, X1, X2, X3)
}

nlogLikWB_ID_theta <- function(para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind) {
    .Call(`_SemiCompRisksFreq_nlogLikWB_ID_theta`, para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind)
}

nlogLikWB_ID_marg <- function(para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind, gauss_nodes, gauss_weights) {
    .Call(`_SemiCompRisksFreq_nlogLikWB_ID_marg`, para, y1, y2, delta1, delta2, X1, X2, X3, yL, anyLT, model, weights, frailty_ind, gauss_nodes, gauss_weights)
}

